version: "3.9"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - '5433:5432'
    expose:
      - '5433'
    volumes:
      - kisledca-db:/var/lib/postgresql
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6380:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - kisledca-cache:/data
volumes:
  kisledca-db:
    driver: local
  kisledca-cache:
    driver: local