version: '3.9'
services:
  mongo:
    image: mongo
    ports: 
      - '27018:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - '1434:1433'
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=123qwe!@#QWE